apiVersion: v1
kind: Deployment
metadata:
  name: filewritter-deployment
  labels:
    app: filewritter-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: filewritter-app
  template:
    metadata:
      labels:
        app: filewritter-app
    spec:
      containers:
        - name: filewritter
          image: halfonx/filewritter-app:0.0.1
          env:
            - name: S3_ENDPOINT
              value: "https://cellar-c2.services.clever-cloud.com"
            - name: S3_ACCESS_KEY_ID
              value: "QD9HR8OK6EL1LO12TYA8"
            - name: S3_SECRET_ACCESS_KEY
              value: "NEXMCPoGbWGnKgGMwvAkTdOO83HcdfvWFzLB6Tpn"
            - name: PORT
              value: "8080"
            - name: MYSQL_ADDON_URI
              value: "mysql://ugjzrq07rg00omrc:aJGOaB92oPoEUM1iC3sF@bu0bzrh2i5ujxxwgfwxn-mysql.services.clever-cloud.com:3306/bu0bzrh2i5ujxxwgfwxn"
          ports:
            - containerPort: 8080
